-- 012_outstanding_payments.sql
-- Creates bookings.outstanding_payments for BillingCycleTrigger.
-- Safe to re-run: all statements use IF NOT EXISTS / DO NOTHING guards.

-- ─── outstanding_payments ────────────────────────────────────────────────────
-- Tracks billing cycle reminders generated by BillingCycleTrigger.
-- One row per billing cycle per rule.  ON CONFLICT guard makes inserts idempotent.
CREATE TABLE IF NOT EXISTS bookings.outstanding_payments (
    id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         INT          NOT NULL,
    recurring_rule_id UUID         NOT NULL,
    customer_id       UUID         NOT NULL,
    period_start      DATE         NOT NULL,
    amount_due        NUMERIC(10,2) NOT NULL DEFAULT 0,
    due_date          DATE,
    status            TEXT         NOT NULL DEFAULT 'pending',
    cycle_number      INT,
    total_cycles      INT,
    email_sent_at     TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_outstanding_payments_rule_period
    ON bookings.outstanding_payments(recurring_rule_id, period_start)
    WHERE status != 'cancelled';

CREATE INDEX IF NOT EXISTS idx_outstanding_payments_tenant
    ON bookings.outstanding_payments(tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_outstanding_payments_customer
    ON bookings.outstanding_payments(customer_id, tenant_id);

-- RLS policy (consistent with 011_rls_phase4.sql pattern)
ALTER TABLE bookings.outstanding_payments ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY outstanding_payments_tenant_isolation
        ON bookings.outstanding_payments
        FOR ALL
        USING (tenant_id = COALESCE(
            current_setting('app.tenant_id', TRUE)::int,
            -1
        ));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
